apiVersion : apps/v1
kind: Deployment
metadata:
  name: authenticationapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationapi
  template:
    metadata:
      labels:
        app: authenticationapi 
    spec:
      containers:
        - name: authenticationapi 
          image: acrvod.azurecr.io/authenticationapi
          ports:
          - containerPort: 80